version: '3.7'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ${db_name}
      MYSQL_USER: ${db_user}
      MYSQL_PASSWORD: ${db_password}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
    - app-network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    environment:
      DB_HOST: ${db_host}
      DB_PORT: 3306
      DB_USER: ${db_user}
      DB_PASSWORD: ${db_password}
      DB_NAME: ${db_name}
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - .:/app

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
